service: energy-stats

variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    user_pool_id: { Ref: UserPool }
    client_id: { Ref: UserClient }
    meter_table: { Ref: meterTable}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminInitiateAuth
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminSetUserPassword
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:DeleteItem
      Resource: "*"
  

plugins:
  - serverless-webpack

custom:
  esbuild:
    bundle: true
    minify: false
  aliasHostedZoneId: Z3AQBSTGFYJSTF    # us-east-1
  aliasDNSName: s3-website-us-east-1.amazonaws.com
  siteName: energy.simonarcher.info
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    includeModules: false # Node modules configuration for packaging
    packager: 'npm' # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore

package:
  individually: false

functions:
  loginUser:
    handler: backend/auth/login.handler
    events:
      - http:
          path: user/login
          method: post
          cors: true
  signupUser:
    handler: backend/auth/signup.handler
    events:
      - http:
          path: user/signup
          method: post
          cors: true
  addMeter:
    handler: backend/meters/addMeter.handler
    events:
      - http:
          path: meters/add-meter
          method: post
          cors: true
  getMeters:
    handler: backend/meters/getMeters.handler
    events:
      - http:
          path: meters/get-meters
          method: get
          cors: true
  deleteMeter:
    handler: backend/meters/deleteMeter.handler
    events:
      - http:
          path: meters/delete-meter
          method: post
          cors: true
  

resources:
  - ${file(./serverless/backend/userPool.yml)}
  - ${file(./serverless/frontend/s3Website.yml)}
  - ${file(./serverless/backend/meterTable.yml)}