service: energy-stats
# plugins: 
#   - serverless-s3-sync

provider:
  name: aws
  runtime: nodejs16.x

custom:
  aliasHostedZoneId: Z3AQBSTGFYJSTF    # us-east-1
  aliasDNSName: s3-website-us-east-1.amazonaws.com
  siteName: energy.simonarcher.info
  # s3Sync:
  #   - bucketName: ${self:custom.siteName}
  #     localDir: build

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.siteName}
        WebsiteConfiguration:
          IndexDocument: index.html
    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource:
                Fn::Join: [
                  "", [
                    "arn:aws:s3:::",
                    {
                      "Ref": "StaticSite"
                    },
                    "/*"
                  ]
                ]
    DnsRecord:
      Type: "AWS::Route53::RecordSetGroup"
      Properties:
        HostedZoneName: simonarcher.info.
        RecordSets:
          - Name: energy.simonarcher.info
            Type: "A"
            AliasTarget:
              DNSName: ${self:custom.aliasDNSName}
              HostedZoneId: ${self:custom.aliasHostedZoneId}